import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import SectionWrapper from "./components/Layouts/SectionWrapper.vue";
import { container } from "./components/Layouts/Container";
import Flex from "./components/Layouts/Flex.vue";
import Grid from "./components/Layouts/Grid.vue";
import AppButton from "./components/UI/AppButton.vue";
import Card from "./components/Layouts/Card.vue";
import FloatImage from "./components/UI/FloatImage.vue";
const app = createApp(App);
app.component("float-image", FloatImage);
app.component("card", Card);
app.component("app-component", AppButton);
app.component("grid", Grid);
app.component("flex", Flex);
app.component("container", container);
app.component("section-wrapper", SectionWrapper);
app.mount("#app");
